import { Area, ItemType, LinkType, Places, TransitMedium } from "./commons.js";

const TransitPlaces = {
	P_BALLY_STATION: {"name": "Bally Station", "gmapsUrl": "https://maps.app.goo.gl/uavYxSJbuMhwrJTH6", "placeType": "rail-station"},
	P_HOWRAH_JUNCTION: {"name": "Howrah Junction", "gmapsUrl": "https://maps.app.goo.gl/fodueEJVNw71SCuZ9", "placeType": "rail-station"},
	P_RASHBEHARI_CROSSING: {"name": "Rashbehari Crossing", "gmapsUrl": "https://maps.app.goo.gl/DbQaVBsoMj6Pr3nL7"},
	P_BALLYGUNGE_JUNCTION: {"name": "Ballygunge Junction", "gmapsUrl": "https://maps.app.goo.gl/RcZAx4MhPK5gpNwf6", "placeType": "rail-station"},
	P_SEALDAH_JUNCTION: {"name": "Sealdah Junction", "gmapsUrl": "https://maps.app.goo.gl/nHU3NUAYAF9BQLRw7", "placeType": "rail-station"},
	P_BIDHANNAGAR_ROAD: {"name": "Bidhannagar Road", "gmapsUrl": "https://maps.app.goo.gl/rTTJmLhsMeULyZGg7", "placeType": "rail-station"},
	P_NAGER_BAZAR: {"name": "Nager Bazar", "gmapsUrl": "https://maps.app.goo.gl/cZvQfnjq9xJcvtcs5", "placeType": "bus-stop"},
	P_DUM_DUM_JUNCTION: {"name": "Dum Dum Junction", "gmapsUrl": "https://maps.app.goo.gl/1DrWe9BvtsXJCQr57", "placeType": "rail-station"},
	P_SINTHIR_MORE: {"name": "Sinthir More", "gmapsUrl": "https://maps.app.goo.gl/GoZMgfrVSuf8JKvj8", "placeType": "bus-stop"},
	P_PALPARA_BUS_STOP: {"name": "Palpara Bus Stop", "gmapsUrl": "https://maps.app.goo.gl/hhBEDgnD255T3YH6A", "placeType": "bus-stop"},
	P_BALLY_HALT: {"name": "Bally Halt", "gmapsUrl": "https://maps.app.goo.gl/UGfT1uTwTogaenT37", "placeType": "bus-stop"},
};

export const saptami = {
	title: "Saptami",
	dateLabel: "18 OCTOBER · SUNDAY",
	meetup: { time: "9:00 AM · Bally Station", place: Places.RAIL_STATIONS.MEET_UP_9_00_AM_BALLY_STATION },
	lunchStop: { type: ItemType.LUNCH, title: "Zeeshan or Sorshe Posto", distance: 0, description: "Choose one of the planned lunch stops.", options: [{ title: "Zeeshan ↗", gmapsUrl: "https://maps.app.goo.gl/hGtgmZqF1UK5F3w8A" }, { title: "Sorshe Posto ↗", gmapsUrl: "https://maps.app.goo.gl/2xknrQkQZ9ZjEFRT9" }] },
	stops: [
		{ order: 1, type: ItemType.PANDAL, area: Area.BALLYGUNGE, title: "Deshapriya Park", distance: 850, gmapsUrl: "https://maps.app.goo.gl/yLuoC1C7TRnwBiDD7", htmlDesc: "Celebrating its <strong>89th year</strong>, the 2026\n\t\t\t\t\t\t\t\t\t\tpresentation takes the form of a\n\t\t\t\t\t\t\t\t\t\t<strong>fictional temple</strong>, featuring multiple\n\t\t\t\t\t\t\t\t\t\tspires, a grand staircase and classical architectural\n\t\t\t\t\t\t\t\t\t\tdetailing. The idol is being created by\n\t\t\t\t\t\t\t\t\t\t<strong>Sanatan Rudra Pal</strong>, with a special lighting\n\t\t\t\t\t\t\t\t\t\tpresentation planned to add to the visual experience.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/Deshapriyaparkdurgotsab" }, { type: LinkType.EMAIL, value: "deshapriyaparkdurgotsab2012@gmail.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.518878,88.3519183,17z?entry=ttu", transit: 0, isPreviousTransit: true },
		{ order: 2, type: ItemType.PANDAL, area: Area.BALLYGUNGE, title: "Tridhara Sammilani", distance: 600, gmapsUrl: "https://maps.app.goo.gl/aMjnACpbi2GXXiqC8", htmlDesc: "Celebrating its <strong>80th year</strong>, this distinctive\n\t\t\t\t\t\t\t\t\t\tSouth Kolkata puja is known for blending tradition with\n\t\t\t\t\t\t\t\t\t\tcontemporary artistic expression. The 2026 presentation\n\t\t\t\t\t\t\t\t\t\tfeatures the officially announced theme\n\t\t\t\t\t\t\t\t\t\t<strong>'Surasur' (সুরাসুর)</strong>, brought to life by\n\t\t\t\t\t\t\t\t\t\tartist <strong>Gauranga Kuilya</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/Tridharaakalbodhan" }, { type: LinkType.WEBSITE, value: "https://www.instagram.com/tridhara_akalbodhan" }, { type: LinkType.WEBSITE, value: "https://www.tridhara.org" }, { type: LinkType.PHONE, value: "8777032919" }, { type: LinkType.EMAIL, value: "tridharaakalbodhan1947@gmail.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5195286,88.3528649,17z?entry=ttu" },
		{ order: 3, type: ItemType.PANDAL, area: Area.BALLYGUNGE, title: "Ballygunge Cultural Association", distance: 1000, gmapsUrl: "https://maps.app.goo.gl/h9e9QiBJ56LQQHpL6", htmlDesc: "Celebrating its <strong>76th year</strong>, the 2026\n\t\t\t\t\t\t\t\t\t\tpresentation features the theme\n\t\t\t\t\t\t\t\t\t\t<strong>'Connection' (যোজন)</strong>. Known for its\n\t\t\t\t\t\t\t\t\t\tdistinctive South Kolkata style blending tradition with\n\t\t\t\t\t\t\t\t\t\tcontemporary artistic expression, the concept is led by\n\t\t\t\t\t\t\t\t\t\tartist <strong>Sushanta Shibani Paul</strong>, supported by\n\t\t\t\t\t\t\t\t\t\ta creative team including Adhir Pal, Lakshman Roy, Suman\n\t\t\t\t\t\t\t\t\t\tMaity, Shirsak Paul, Samir Mondal, Tapan Maji, Gopal Mondal,\n\t\t\t\t\t\t\t\t\t\tBikas Sardar, Tuhin Das, Nepal Maity, Goutam Das, and Tokan\n\t\t\t\t\t\t\t\t\t\tDas.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/BCA1951" }, { type: LinkType.PHONE, value: "9836155564" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5162122,88.353231,17z?entry=ttu" },
		{ order: 4, type: ItemType.PANDAL, area: Area.BALLYGUNGE, title: "Samaj Sebi Sangha", distance: 120, gmapsUrl: "https://maps.app.goo.gl/t2AigUpcESPqpbo59", htmlDesc: "Celebrating its <strong>81st year</strong>, the Puja pays\n\t\t\t\t\t\t\t\t\t\ttribute to Uttam Kumar's birth centenary through\n\t\t\t\t\t\t\t\t\t\t<strong>'Mahapujoy Mahanayak' (মহাপুজোয় মহানায়ক)</strong>.\n\t\t\t\t\t\t\t\t\t\tThe presentation recreates the nostalgia of\n\t\t\t\t\t\t\t\t\t\t<strong>1970s-80s Kolkata</strong>, bringing together film\n\t\t\t\t\t\t\t\t\t\tposters, photographs, memorabilia and stories from the\n\t\t\t\t\t\t\t\t\t\tlegendary actor's life. <strong>Bishwanath Dey</strong> is\n\t\t\t\t\t\t\t\t\t\tthe theme-maker, with the idol by\n\t\t\t\t\t\t\t\t\t\t<strong>Arighna Saha</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/samajsebisangha" }, { type: LinkType.WEBSITE, value: "https://www.instagram.com/samaj_sebi" }, { type: LinkType.PHONE, value: "9830035979" }, { type: LinkType.EMAIL, value: "arijitmaitra5@gmail.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5157267,88.3537228,17z?entry=ttu", lunch: true },
		{ order: 5, type: ItemType.PANDAL, area: Area.GARIAHAT, title: "Hindustan Park", distance: 1100, gmapsUrl: "https://maps.app.goo.gl/mpQJBPSC8QbaEETx8", htmlDesc: "Celebrating its <strong>96th year</strong>, the 2026\n\t\t\t\t\t\t\t\t\t\tpresentation features the theme\n\t\t\t\t\t\t\t\t\t\t<strong>'Spark' (স্ফুলিঙ্গ)</strong>, placing emphasis on\n\t\t\t\t\t\t\t\t\t\tBengali craftsmanship and intricate handwork. The\n\t\t\t\t\t\t\t\t\t\tinstallation is brought to life by a creative team including\n\t\t\t\t\t\t\t\t\t\t<strong>Malay Subhomoy, Premendu Bikash Chaki, and Dipamoy\n\t\t\t\t\t\t\t\t\t\t\tDas</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/profile.php?id=100057277397392" }, { type: LinkType.PHONE, value: "9831598966" }, { type: LinkType.EMAIL, value: "hindustanpark@gmail.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5176792,88.3594967,17z?entry=ttu" },
		{ order: 6, type: ItemType.PANDAL, area: Area.GARIAHAT, title: "Gariahat Hindustan Club", distance: 450, gmapsUrl: "https://maps.app.goo.gl/k4aa46StnX8P9qsi7", htmlDesc: "Celebrating its <strong>64th year</strong>, this\n\t\t\t\t\t\t\t\t\t\tlong-running Gariahat Puja continues its history of\n\t\t\t\t\t\t\t\t\t\ttraditional and colourful artistic presentations. The 2026\n\t\t\t\t\t\t\t\t\t\tpresentation features the theme\n\t\t\t\t\t\t\t\t\t\t<strong>'Durga Dalan' (দুর্গা দালান)</strong>,\n\t\t\t\t\t\t\t\t\t\tconceptualised by creative artist\n\t\t\t\t\t\t\t\t\t\t<strong>Raju Sarkar</strong>, supported by lighting design\n\t\t\t\t\t\t\t\t\t\tfrom <strong>Ashok Das and Chitralekha Pal</strong>, and\n\t\t\t\t\t\t\t\t\t\tdecorations by <strong>Golden Decorator</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/gariahat.hindusthanclub" }, { type: LinkType.WEBSITE, value: "https://www.instagram.com/gariahathindusthanclub" }, { type: LinkType.PHONE, value: "9051336557" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5201571,88.3583349,17z?entry=ttu" },
		{ order: 7, type: ItemType.PANDAL, area: Area.GARIAHAT, title: "Singhi Park", distance: 700, gmapsUrl: "https://maps.app.goo.gl/B9obxmiXbv3HBuAAA", htmlDesc: "Celebrating its <strong>85th year</strong>, this established\n\t\t\t\t\t\t\t\t\t\tGariahat Puja maintains a strong community and traditional\n\t\t\t\t\t\t\t\t\t\tidentity. The 2026 presentation features the theme\n\t\t\t\t\t\t\t\t\t\t<strong>'Bostario' (বস্তারীয়)</strong>, conceptualised by\n\t\t\t\t\t\t\t\t\t\t<strong>Ankita Bandyopadhyay</strong>, with an idol crafted\n\t\t\t\t\t\t\t\t\t\tby <strong>Pradip Rudra Pal</strong> and a background score\n\t\t\t\t\t\t\t\t\t\tby <strong>Subhen Chattopadhyay</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/SinghiParkSarbojaninDurgaPujaCommittee" }, { type: LinkType.WEBSITE, value: "https://www.instagram.com/singhipark" }, { type: LinkType.EMAIL, value: "info@singhipark.in" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5209489,88.3601532,17z?entry=ttu" },
		{ order: 8, type: ItemType.PANDAL, area: Area.GARIAHAT, title: "Ekdalia Evergreen", distance: 350, gmapsUrl: "https://maps.app.goo.gl/RcZAx4MhPK5gpNwf6", htmlDesc: "Celebrating its <strong>84th year</strong>, the Puja retains\n\t\t\t\t\t\t\t\t\t\tits iconic <strong>Sabeki idol</strong> while taking\n\t\t\t\t\t\t\t\t\t\tinspiration from Gujarat's magnificent\n\t\t\t\t\t\t\t\t\t\t<strong>Somnath Temple</strong> for the 2026 pandal. The\n\t\t\t\t\t\t\t\t\t\ttemple-inspired architecture provides the year's major\n\t\t\t\t\t\t\t\t\t\tvisual attraction, while the traditional idol remains at the\n\t\t\t\t\t\t\t\t\t\theart of the Puja.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/ekdaliaevergreen" }, { type: LinkType.PHONE, value: "9831095622" }, { type: LinkType.EMAIL, value: "evergreenclub43.ekdalia@gmail.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5212187,88.363988,17z?entry=ttu", transit: 1 },
		{ order: 9, type: ItemType.PANDAL, area: Area.ULTADANGA, title: "Karbagan", distance: 850, gmapsUrl: "https://maps.app.goo.gl/hstyw78otaNe7CjA8", htmlDesc: "Celebrating its <strong>79th year</strong>, the 2026\n\t\t\t\t\t\t\t\t\t\tpresentation for this Ultadanga puja features the theme\n\t\t\t\t\t\t\t\t\t\t<strong>'Jay Bhawani' (জয় ভবানী)</strong>, brought to life\n\t\t\t\t\t\t\t\t\t\tby <strong>Saurav Saha and Team</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/profile.php?id=100073478138148" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5951861,88.3836376,17z?entry=ttu" },
		{ order: 10, type: ItemType.PANDAL, area: Area.ULTADANGA, title: "Pallyshree", distance: 100, gmapsUrl: "https://maps.app.goo.gl/5gBviF119Ptf545z6", htmlDesc: "Celebrating its <strong>78th year</strong>, the 2026\n\t\t\t\t\t\t\t\t\t\tpresentation features the theme\n\t\t\t\t\t\t\t\t\t\t<strong>'Olot Palot' (ওলট পালট)</strong>. The artistic\n\t\t\t\t\t\t\t\t\t\tdirection is advised by <strong>Malay and Subhamay</strong>,\n\t\t\t\t\t\t\t\t\t\twith the visual setup and execution collaboratively handled\n\t\t\t\t\t\t\t\t\t\tby <strong>Utsav Hut</strong> alongside\n\t\t\t\t\t\t\t\t\t\t<strong>Naba Kumar Pal, Subimal Das, and Amarnath Das</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/profile.php?id=100063896414260" }, { type: LinkType.PHONE, value: "9830561561" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5958272,88.3827102,17z?entry=ttu" },
		{ order: 11, type: ItemType.PANDAL, area: Area.ULTADANGA, title: "Telengabagan", distance: 350, gmapsUrl: "https://maps.app.goo.gl/iJjguSwkSZW517p49", htmlDesc: "Celebrating its <strong>61st year</strong>, the 2026\n\t\t\t\t\t\t\t\t\t\tpresentation features the theme\n\t\t\t\t\t\t\t\t\t\t<strong>'Tilottamar Olinder Iti Kotha' (তিলোত্তমার অলিন্দের\n\t\t\t\t\t\t\t\t\t\t\tইতিকথা)</strong>. The concept is envisioned by <strong>Prasanta</strong>,\n\t\t\t\t\t\t\t\t\t\twith the idol crafted by <strong>Parimal Pal</strong>, and\n\t\t\t\t\t\t\t\t\t\tmusic composed by\n\t\t\t\t\t\t\t\t\t\t<strong>Anupam Mistri and Sanjay Sarkar</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/telengabagansarbojonin" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5949469,88.3849412,17z?entry=ttu" },
		{ order: 12, type: ItemType.PANDAL, area: Area.ULTADANGA, title: "Jagarani Sangha", distance: 260, gmapsUrl: "https://maps.app.goo.gl/sG8dNKqfsCeAbun28", htmlDesc: "Celebrating its <strong>33rd year</strong>, the 2026\n\t\t\t\t\t\t\t\t\t\tpresentation for this Ultadanga puja features the theme\n\t\t\t\t\t\t\t\t\t\t<strong>'Tulir tane Simontini' (তুলির টানে সীমন্তিনী)</strong>. The overall concept and arrangement are envisioned by\n\t\t\t\t\t\t\t\t\t\t<strong>Paritosh Talukdar</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/UltadangaJagaraniSanghaOfficial" }, { type: LinkType.PHONE, value: "9874438160" }, { type: LinkType.EMAIL, value: "ultadangajagaranisangha@gmail.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.59351,88.3845229,17z?entry=ttu" },
		{ order: 13, type: ItemType.PANDAL, area: Area.ULTADANGA, title: "Surirbagan", distance: 400, gmapsUrl: "https://maps.app.goo.gl/o1jkHjKpXiBgwbyaA", htmlDesc: "A neighbourhood Puja in the Bidhannagar area with an\n\t\t\t\t\t\t\t\t\t\testablished community presence. A reliable\n\t\t\t\t\t\t\t\t\t\t<strong>2026 theme or artist announcement has not yet been\n\t\t\t\t\t\t\t\t\t\t\tconfirmed</strong>, so no unsupported creative details are included here.", links: [], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5948381,88.3842146,17z?entry=ttu" },
		{ order: 14, type: ItemType.PANDAL, area: Area.ULTADANGA, title: "Sangrami Sangha", distance: 1200, gmapsUrl: "https://maps.app.goo.gl/65xrZdH784LpN4zB9", htmlDesc: "Celebrating its <strong>64th year</strong>, the 2026\n\t\t\t\t\t\t\t\t\t\tpresentation for this Ultadanga puja features the theme\n\t\t\t\t\t\t\t\t\t\t<strong>'Roktokorobi' (রক্তকরবী)</strong>. The concept is\n\t\t\t\t\t\t\t\t\t\tenvisioned by <strong>Arindam and Tanushree</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/profile.php?id=100083241553607" }, { type: LinkType.WEBSITE, value: "https://www.instagram.com/ultadangasangrami" }, { type: LinkType.PHONE, value: "6290987035" }, { type: LinkType.EMAIL, value: "sangrami1966@gmail.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5909721,88.3932635,17z?entry=ttu", transit: 2 },
		{ order: 15, type: ItemType.PANDAL, area: Area.NAGER_BAZAR, title: "Yuba Sangha", distance: 400, gmapsUrl: "https://maps.app.goo.gl/pRbwoarxRR9vgDU88", htmlDesc: "Stepping into a large-scale thematic presentation for the\n\t\t\t\t\t\t\t\t\t\tfirst time, this puja is generating significant hype and\n\t\t\t\t\t\t\t\t\t\tenthusiasm among pandal hoppers. The 2026 presentation\n\t\t\t\t\t\t\t\t\t\tfeatures the theme\n\t\t\t\t\t\t\t\t\t\t<strong>'Ek Pukur Bhalobasa' (এক পুকুর ভালোবাসা)</strong>,\n\t\t\t\t\t\t\t\t\t\tconceptualised and brought to life by renowned artist\n\t\t\t\t\t\t\t\t\t\t<strong>Bhabotosh Sutar</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/yubasanghatelipukur" }, { type: LinkType.WEBSITE, value: "https://www.instagram.com/yubasangha1957" }, { type: LinkType.WEBSITE, value: "https://www.youtube.com/@YubasanghaClub" }, { type: LinkType.PHONE, value: "7003993519" }, { type: LinkType.EMAIL, value: "yubasangha1957@gmail.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.621507,88.4107941,17z?entry=ttu", transit: 3 },
		{ order: 16, type: ItemType.PANDAL, area: Area.BARANAGAR, title: "Bandhudal Sporting Club", distance: 150, gmapsUrl: "https://maps.app.goo.gl/mFwWnFcywc9LEZVf7", htmlDesc: "Celebrating its <strong>65th year</strong>, Bandhudal\n\t\t\t\t\t\t\t\t\t\tSporting Club presents the 2026 theme\n\t\t\t\t\t\t\t\t\t\t<strong>Lotus Temple</strong>. The creative concept is\n\t\t\t\t\t\t\t\t\t\tenvisioned by <strong>Shibsankar Das</strong> and executed\n\t\t\t\t\t\t\t\t\t\tby <strong>Bidyut Pal</strong>, featuring an idol crafted by\n\t\t\t\t\t\t\t\t\t\t<strong>Mintu Pal</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/bandhudalsportingclub" }, { type: LinkType.WEBSITE, value: "https://www.youtube.com/@bandhudalsportingclub" }, { type: LinkType.PHONE, value: "8910482723" }, { type: LinkType.EMAIL, value: "bandhudalsportingclub@gmail.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.6327969,88.3757876,17z?entry=ttu" },
		{ order: 17, type: ItemType.PANDAL, area: Area.BARANAGAR, title: "Karmi Sangha", distance: 650, gmapsUrl: "https://maps.app.goo.gl/UP9sEshkDXq6Z9r37", htmlDesc: "Celebrating its <strong>75th year</strong>, the 2026\n\t\t\t\t\t\t\t\t\t\tpresentation for this Ultadanga puja features the theme\n\t\t\t\t\t\t\t\t\t\t<strong>'Swarnabasar' (স্বর্ণবাসর)</strong>. The concept and\n\t\t\t\t\t\t\t\t\t\tidol are crafted by <strong>Indrajit Poddar</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/karmisangha1" }, { type: LinkType.PHONE, value: "9836122236" }, { type: LinkType.EMAIL, value: "karmisangha@gmail.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.6351084,88.3740195,17z?entry=ttu" },
		{ order: 18, type: ItemType.PANDAL, area: Area.BARANAGAR, title: "Barangar Netaji Colony Lowland", distance: 1000, gmapsUrl: "https://maps.app.goo.gl/ptXYQFfNnLrJjogv5", htmlDesc: "Celebrating its <strong>5th year</strong>, this relatively\n\t\t\t\t\t\t\t\t\t\tyoung but rapidly rising Durga Puja in Baranagar is already\n\t\t\t\t\t\t\t\t\t\tmaking its mark on the local circuit. While the\n\t\t\t\t\t\t\t\t\t\t<strong>final 2026 theme is not yet confirmed</strong>,\n\t\t\t\t\t\t\t\t\t\tongoing preparations reveal beautiful and intricate plywood\n\t\t\t\t\t\t\t\t\t\tstructures currently taking shape.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/nclowlanddurgotsab" }, { type: LinkType.PHONE, value: "9470500704" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.6354717,88.3807602,17z?entry=ttu", transit: 4 }
	],
	transits: [
		{ index: 0, steps: [{ order: 1, medium: TransitMedium.TRAIN, src: TransitPlaces.P_BALLY_STATION, dest: TransitPlaces.P_HOWRAH_JUNCTION }, { order: 2, medium: TransitMedium.BUS, src: TransitPlaces.P_HOWRAH_JUNCTION, dest: TransitPlaces.P_RASHBEHARI_CROSSING }] },
		{ index: 1, steps: [{ order: 1, medium: TransitMedium.TRAIN, src: TransitPlaces.P_BALLYGUNGE_JUNCTION, dest: TransitPlaces.P_SEALDAH_JUNCTION }, { order: 2, medium: TransitMedium.TRAIN, src: TransitPlaces.P_SEALDAH_JUNCTION, dest: TransitPlaces.P_BIDHANNAGAR_ROAD, service: "any train" }, { order: 3, medium: TransitMedium.BUS, src: TransitPlaces.P_BIDHANNAGAR_ROAD, dest: TransitPlaces.P_NAGER_BAZAR }] },
		{ index: 2, steps: [{ order: 1, medium: TransitMedium.WALK, distance: 600, prefix: "Walk back", dest: TransitPlaces.P_BIDHANNAGAR_ROAD }, { order: 2, medium: TransitMedium.TRAIN, src: TransitPlaces.P_BIDHANNAGAR_ROAD, dest: TransitPlaces.P_DUM_DUM_JUNCTION, service: "any train" }, { order: 3, medium: TransitMedium.BUS, src: TransitPlaces.P_DUM_DUM_JUNCTION, dest: TransitPlaces.P_NAGER_BAZAR }] },
		{ index: 3, steps: [{ order: 1, medium: TransitMedium.WALK, distance: 400, prefix: "Walk back", dest: TransitPlaces.P_NAGER_BAZAR }, { order: 2, medium: TransitMedium.BUS, src: TransitPlaces.P_NAGER_BAZAR, dest: TransitPlaces.P_SINTHIR_MORE }] },
		{ index: 4, steps: [{ order: 1, medium: TransitMedium.BUS, src: TransitPlaces.P_PALPARA_BUS_STOP, dest: TransitPlaces.P_BALLY_HALT }] }
	],
};
