import { Area, ItemType, LinkType, Places, TransitMedium } from "./commons.js";

const TransitPlaces = {
	P_SONARPUR_JUNCTION: {"name": "Sonarpur Junction", "gmapsUrl": "https://maps.app.goo.gl/8LoWVUE9gNdAG7dBA", "placeType": "rail-station"},
	P_BAGBAZAR_SARBOJANIN: {"name": "Bagbazar Sarbojanin", "gmapsUrl": "https://maps.app.goo.gl/5tL5FGYAmodbtzb28"},
	P_SOVABAZAR_METRO_STATION: {"name": "Sovabazar Metro Station", "gmapsUrl": "https://maps.app.goo.gl/CfjzpQb3YW9s32tF9", "placeType": "metro-station"},
	P_JORASANKO_THAKUR_BARI: {"name": "Jorasanko Thakur Bari", "gmapsUrl": "https://maps.app.goo.gl/GASUhYS286WtCFKK7"},
	P_RAM_MANDIR: {"name": "Ram Mandir", "gmapsUrl": "https://maps.app.goo.gl/dzf2Fku6mtZMafaK8"},
	P_CHALTA_BAGAN: {"name": "Chalta Bagan", "gmapsUrl": "https://maps.app.goo.gl/bwVoc9AvHERDAxCD8"},
	P_SOVABAZAR_RAJBARI: {"name": "Sovabazar Rajbari", "gmapsUrl": "https://maps.app.goo.gl/hdLF2o85A5YrR7JE9"},
};

export const shashthi = {
	title: "Shashthi",
	dateLabel: "17 OCTOBER · SATURDAY",
	meetup: { time: "9:00 AM · Sonarpur Junction", place: Places.RAIL_STATIONS.SONARPUR_JUNCTION },
	lunchStop: { type: ItemType.LUNCH, title: "Bhojohori Manna", distance: 450, description: "Lunch stop before the afternoon circuit. 🚶 450 m · ⏱️ 9 min\n\t\t\t\t\t\t\t\t\t\tfrom Kashi Bose Lane.", options: [{ title: "Google Maps ↗", gmapsUrl: "https://maps.app.goo.gl/dKruzE6V6zt49Vvw5" }], fromName: "Kashi Bose Lane", gmapsUrl: "https://maps.app.goo.gl/dKruzE6V6zt49Vvw5" },
	stops: [
		{ order: 1, type: ItemType.PANDAL, area: Area.BAGBAZAR, title: "Bagbazar Sarbojanin", distance: 0, gmapsUrl: "https://maps.app.goo.gl/5tL5FGYAmodbtzb28", htmlDesc: "Celebrating its <strong>108th year</strong>, this iconic\n\t\t\t\t\t\t\t\t\t\theritage puja is renowned for its traditional\n\t\t\t\t\t\t\t\t\t\t<strong>Sabeki idol</strong> and timeless cultural\n\t\t\t\t\t\t\t\t\t\tsignificance. Eschewing modern themes, it continues to\n\t\t\t\t\t\t\t\t\t\tpreserve the authentic spirit and grandeur of Kolkata's\n\t\t\t\t\t\t\t\t\t\tclassic Durga Puja celebrations.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/BaghbazarSarbojaninDurgotsavExhibition" }, { type: LinkType.WEBSITE, value: "https://www.bsde.org" }, { type: LinkType.PHONE, value: "9830704299" }, { type: LinkType.EMAIL, value: "info@bsde.org" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.6045484,88.365572,17z?entry=ttu", transit: 0, isPreviousTransit: true },
		{ order: 2, type: ItemType.PANDAL, area: Area.SHYAMBAZAR, title: "Jagat Mukherjee Park", distance: 750, gmapsUrl: "https://maps.app.goo.gl/ouNxifC8yhwvBeNo8", htmlDesc: "Celebrating its <strong>90th year</strong>, this North\n\t\t\t\t\t\t\t\t\t\tKolkata puja features the theme\n\t\t\t\t\t\t\t\t\t\t<strong>'Shankar Nama' (শঙ্কর নামা)</strong>, narrated by\n\t\t\t\t\t\t\t\t\t\t<strong>Avijit Ghatak</strong>, with an idol crafted by\n\t\t\t\t\t\t\t\t\t\t<strong>Amal Paul</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/jagatmukherjipark" }, { type: LinkType.WEBSITE, value: "https://www.jagatmukherjeepark.com" }, { type: LinkType.WEBSITE, value: "https://www.youtube.com/@jagatmukherjeepark" }, { type: LinkType.PHONE, value: "8240037520" }, { type: LinkType.EMAIL, value: "jagatmukherjeepark@gmail.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5995488,88.36574,17z?entry=ttu" },
		{ order: 3, type: ItemType.PANDAL, area: Area.KUMARTULI, title: "Kumartuli Sarbojanin", distance: 500, gmapsUrl: "https://maps.app.goo.gl/64vfpoChDztgBHQJ6", htmlDesc: "Celebrating its <strong>96th year</strong>, the 2026\n\t\t\t\t\t\t\t\t\t\tpresentation features the theme\n\t\t\t\t\t\t\t\t\t\t<strong>'Mon Diye Dekhun' (মন দিয়ে দেখুন)</strong>,\n\t\t\t\t\t\t\t\t\t\tconceptualised by <strong>Manas Roy</strong>, with an idol\n\t\t\t\t\t\t\t\t\t\tcrafted by <strong>Dipankar Pal</strong>, lighting by\n\t\t\t\t\t\t\t\t\t\t<strong>S B Electric</strong>, and pandal decoration by\n\t\t\t\t\t\t\t\t\t\t<strong>S B Decorator</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/kumartulisarbojaninofficial" }, { type: LinkType.WEBSITE, value: "https://www.instagram.com/kumartulisarbojaninofficial" }, { type: LinkType.WEBSITE, value: "https://kumartulysarbojanin.com" }, { type: LinkType.PHONE, value: "9804145557" }, { type: LinkType.EMAIL, value: "kumartulysarbojanin@gmail.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.6001009,88.3593147,17z?entry=ttu" },
		{ order: 4, type: ItemType.PANDAL, area: Area.KUMARTULI, title: "Kumartuli Park", distance: 300, gmapsUrl: "https://maps.app.goo.gl/y4KyRU7dvgBHfJFY9", htmlDesc: "Celebrating its <strong>34th year</strong>, the 2026\n\t\t\t\t\t\t\t\t\t\tpresentation features the theme\n\t\t\t\t\t\t\t\t\t\t<strong>'Gangotri theke Ganga' (গঙ্গোত্রী থেকে গঙ্গা)</strong>, tracing the journey of the Ganga from its Himalayan\n\t\t\t\t\t\t\t\t\t\torigin towards the Bay of Bengal. The concept, brought to\n\t\t\t\t\t\t\t\t\t\tlife by <strong>Subol Pal</strong>, gives the pandal a\n\t\t\t\t\t\t\t\t\t\tstrong connection with India's cultural and spiritual\n\t\t\t\t\t\t\t\t\t\trelationship with the river.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/profile.php?id=100069907448030" }, { type: LinkType.PHONE, value: "7980001710" }, { type: LinkType.EMAIL, value: "kpsdc1993@gmail.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5992933,88.3609198,17z?entry=ttu" },
		{ order: 5, type: ItemType.PANDAL, area: Area.HATKHOLA, title: "Hatkhola Gosaipara Sarbojanin", distance: 250, gmapsUrl: "https://maps.app.goo.gl/D3aYKrWzdPANoiNz8", htmlDesc: "Celebrating its <strong>90th year</strong>, this\n\t\t\t\t\t\t\t\t\t\tneighbourhood puja in the historic North Kolkata belt is\n\t\t\t\t\t\t\t\t\t\tknown for its local Puja atmosphere and place within the\n\t\t\t\t\t\t\t\t\t\t<strong>Kumortuli-Hatkhola circuit</strong>. The 2026\n\t\t\t\t\t\t\t\t\t\tpresentation features the theme\n\t\t\t\t\t\t\t\t\t\t<strong>'Punoragomon' (পুনরাগমন)</strong>, conceptualised by\n\t\t\t\t\t\t\t\t\t\t<strong>Ajit Pal</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/HGSDS1936" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5990953,88.3567291,17z?entry=ttu" },
		{ order: 6, type: ItemType.PANDAL, area: Area.AHIRITOLA, title: "Ahiritola Sarbojanin", distance: 800, gmapsUrl: "https://maps.app.goo.gl/K169ntsPFnMWLkjw7", htmlDesc: "Celebrating its <strong>87th year</strong>, the 2026\n\t\t\t\t\t\t\t\t\t\tpresentation follows a\n\t\t\t\t\t\t\t\t\t\t<strong>Sabeki/traditional direction</strong> with the theme\n\t\t\t\t\t\t\t\t\t\t<strong>'Shoroter Prothom Spondon' (শরতের প্রথম স্পন্দন)</strong>. The concept and creation are handled by\n\t\t\t\t\t\t\t\t\t\t<strong>Manas Das</strong>, featuring an idol crafted by\n\t\t\t\t\t\t\t\t\t\t<strong>Subrata Mridha</strong> and lighting designed by\n\t\t\t\t\t\t\t\t\t\t<strong>Soumen Chakraborty</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/AHIRITOLASARBOJANIN" }, { type: LinkType.WEBSITE, value: "https://www.instagram.com/ahiritolasarbojanin" }, { type: LinkType.PHONE, value: "9831598300" }, { type: LinkType.EMAIL, value: "ahiritolasdurgotsabskol@gmail.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5948383,88.3546998,17z?entry=ttu" },
		{ order: 7, type: ItemType.PANDAL, area: Area.AHIRITOLA, title: "Ahiritola Jubak Brinda", distance: 350, gmapsUrl: "https://maps.app.goo.gl/oeN7Ff7Fwm8cWV2X9", htmlDesc: "Celebrating its <strong>56th year</strong>, this\n\t\t\t\t\t\t\t\t\t\tlong-running Ahiritola puja features the theme\n\t\t\t\t\t\t\t\t\t\t<strong>'Sesh Belay Rabir Alo' (শেষ বেলায় রবির আলো)</strong>, with art direction by <strong>Abhijit Ghatak</strong> and\n\t\t\t\t\t\t\t\t\t\tresearch by <strong>Susobhan Adhikari</strong>. The 2026\n\t\t\t\t\t\t\t\t\t\tpresentation is brought to life by a dedicated team\n\t\t\t\t\t\t\t\t\t\tincluding\n\t\t\t\t\t\t\t\t\t\t<strong>Somnath, Sudarshan, Sukumar, Samir, Bapi, Baburam, Sumon,\n\t\t\t\t\t\t\t\t\t\t\tand Prasanta</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/ahiritolajubakbrinda" }, { type: LinkType.WEBSITE, value: "https://www.instagram.com/ahiritola_jubak_brinda1971" }, { type: LinkType.PHONE, value: "9883065346" }, { type: LinkType.EMAIL, value: "assajb@gmail.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5946791,88.3576368,17z?entry=ttu", transit: 1 },
		{ order: 8, type: ItemType.PANDAL, area: Area.CHORBAGAN, title: "Chorbagan Sarbojanin", distance: 240, gmapsUrl: "https://maps.app.goo.gl/s5cy872mZqXFHufD7", htmlDesc: "Celebrating its <strong>91st year</strong>, the 2026\n\t\t\t\t\t\t\t\t\t\tpresentation features the theme\n\t\t\t\t\t\t\t\t\t\t<strong>'Beyond Sound - অরব'</strong>, conceptualised by\n\t\t\t\t\t\t\t\t\t\tlistener <strong>Sushanta Shibani Paul</strong>. This\n\t\t\t\t\t\t\t\t\t\thistoric North Kolkata puja is brought to life by a\n\t\t\t\t\t\t\t\t\t\tdedicated creative team including\n\t\t\t\t\t\t\t\t\t\t<strong>Adhir Pal, Sujata Kar Saha, Lakshman Roy, Tapan Maji,\n\t\t\t\t\t\t\t\t\t\t\tSuman Maity, Shirshak Paul, Nandadulal Adhikary, Nepal\n\t\t\t\t\t\t\t\t\t\t\tMaity, Ashok Roy Karmakar, Suvendu Guin, and Tokan\n\t\t\t\t\t\t\t\t\t\t\tDas</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/profile.php?id=61592332442890" }, { type: LinkType.WEBSITE, value: "https://www.instagram.com/chorebagansarbojaninofficial" }, { type: LinkType.PHONE, value: "9073980535" }, { type: LinkType.EMAIL, value: "chorebagansarbojaninofficial@gmail.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5834844,88.3628423,17z?entry=ttu", transit: 2 },
		{ order: 9, type: ItemType.PANDAL, area: Area.MANIKTALA, title: "Maniktala Chalta Bagan Lohapatty", distance: 240, gmapsUrl: "https://maps.app.goo.gl/edCK72FtZFGgRLLU8", htmlDesc: "Celebrating its <strong>84th year</strong>, the 2026\n\t\t\t\t\t\t\t\t\t\tpresentation features the theme\n\t\t\t\t\t\t\t\t\t\t<strong>'Aditi' (অদিতি)</strong>, brought to life by\n\t\t\t\t\t\t\t\t\t\tcreative artists <strong>Pallab and Arpan</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/chaltabagan" }, { type: LinkType.WEBSITE, value: "http://manicktallachaltabaganlohapattydurgapuja.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5848905,88.3715554,17z?entry=ttu" },
		{ order: 10, type: ItemType.PANDAL, area: Area.MANIKTALA, title: "Lalabagan Sarbojonin", distance: 800, gmapsUrl: "https://maps.app.goo.gl/Sqk7jdCnsP9oAmvb8", htmlDesc: "Celebrating its <strong>79th year</strong>, this well-known\n\t\t\t\t\t\t\t\t\t\tManiktala area puja features the theme\n\t\t\t\t\t\t\t\t\t\t<strong>'Purush Manei Dayitto' (পুরুষ মানেই দায়িত্ব)</strong>, with arrangement and concept by\n\t\t\t\t\t\t\t\t\t\t<strong>Babusona</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/Sammilita.Lalabagan.Sarbojanin.Durgotsav.Committee" }, { type: LinkType.WEBSITE, value: "https://x.com/S_Lalabagan" }, { type: LinkType.PHONE, value: "8910047936" }, { type: LinkType.EMAIL, value: "sammilita.lalabagan@gmail.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5873617,88.3744003,17z?entry=ttu" },
		{ order: 11, type: ItemType.PANDAL, area: Area.MANIKTALA, title: "Lalabagan Nabankur", distance: 50, gmapsUrl: "https://maps.app.goo.gl/WPbZGm7zVBvvyc4c9", htmlDesc: "Celebrating its <strong>67th year</strong>, this well-known\n\t\t\t\t\t\t\t\t\t\tManiktala area puja features the theme\n\t\t\t\t\t\t\t\t\t\t<strong>'শিকড় - a historic root'</strong>. The 2026\n\t\t\t\t\t\t\t\t\t\tpresentation is brought to life by a creative team including\n\t\t\t\t\t\t\t\t\t\t<strong>Susobhon, Debraj, Rohan, Riku, Chitralekh, and\n\t\t\t\t\t\t\t\t\t\t\tBampai</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/lalabagannabankurofficial" }, { type: LinkType.WEBSITE, value: "https://www.instagram.com/lalabagannabankur_official" }, { type: LinkType.PHONE, value: "9163031118" }, { type: LinkType.EMAIL, value: "lalabagannabankur1961@gmail.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5875607,88.3743587,17z?entry=ttu" },
		{ order: 12, type: ItemType.PANDAL, area: Area.GOURIBARI, title: "Gouriberia Sarbojonin", distance: 800, gmapsUrl: "https://maps.app.goo.gl/LcBeGpwUgg9BJCuD9", htmlDesc: "Celebrating its <strong>93rd year</strong>, this well-known\n\t\t\t\t\t\t\t\t\t\tManiktala area puja features the theme\n\t\t\t\t\t\t\t\t\t\t<strong>'Bankim' (বঙ্কিম)</strong>. The 2026 presentation is\n\t\t\t\t\t\t\t\t\t\tconceptualised by <strong>Madhurima Bhattacharya</strong>,\n\t\t\t\t\t\t\t\t\t\twith an idol crafted by <strong>Sanatan Rudra Pal</strong>,\n\t\t\t\t\t\t\t\t\t\tbackground music by <strong>Saikat Deb</strong>, and\n\t\t\t\t\t\t\t\t\t\tlighting directed by <strong>Kunal Pathak</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/GSDOP" }, { type: LinkType.PHONE, value: "9331003711" }, { type: LinkType.EMAIL, value: "info@gouriberia.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5915219,88.365696,17z?entry=ttu" },
		{ order: 13, type: ItemType.PANDAL, area: Area.HATIBAGAN, title: "Kashi Bose Lane", distance: 1400, gmapsUrl: "https://maps.app.goo.gl/H1ZWF7LL37H1gagM8", htmlDesc: "Celebrating its <strong>89th year</strong>, the specific\n\t\t\t\t\t\t\t\t\t\ttheme for the 2026 presentation has not been disclosed yet.\n\t\t\t\t\t\t\t\t\t\tThe overall concept and planning are being helmed by\n\t\t\t\t\t\t\t\t\t\t<strong>Anirban Das</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/kashiboselanedurgapujasamity" }, { type: LinkType.WEBSITE, value: "https://www.kashiboselane.com" }, { type: LinkType.PHONE, value: "8777094525" }, { type: LinkType.EMAIL, value: "kashiboselane@gmail.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.590898,88.3665361,17z?entry=ttu", lunch: true },
		{ order: 14, type: ItemType.PANDAL, area: Area.HATIBAGAN, title: "Hatibagan Sarbojanin", distance: 170, gmapsUrl: "https://maps.app.goo.gl/rur2n3pKQ48h91vR9", htmlDesc: "Celebrating its <strong>92nd year</strong>, this\n\t\t\t\t\t\t\t\t\t\trecognisable North Kolkata puja features the theme\n\t\t\t\t\t\t\t\t\t\t<strong>'Rhythmless Orderless' (ছন্দছাড়া ছন্নছাড়া)</strong>. The 2026 presentation is brought to life by a creative\n\t\t\t\t\t\t\t\t\t\tteam including\n\t\t\t\t\t\t\t\t\t\t<strong>Rabin Roy, Surajit Pal, Ayan Mukherjee, Nandadulal\n\t\t\t\t\t\t\t\t\t\t\tAdhikari, Lakshman Roy, and Suman Maity</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/HatibaganSarbojaninDurgotsav" }, { type: LinkType.WEBSITE, value: "https://www.instagram.com/hatibagan_sarbojanin_durgotsav" }, { type: LinkType.PHONE, value: "9433052274" }, { type: LinkType.EMAIL, value: "hatibagansarbojonin@gmail.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5943327,88.3717207,17z?entry=ttu" },
		{ order: 15, type: ItemType.PANDAL, area: Area.HATIBAGAN, title: "Nalin Sarkar Street", distance: 270, gmapsUrl: "https://maps.app.goo.gl/ubHt8KwiYY6mu7fS9", htmlDesc: "Celebrating its <strong>94th year</strong>, the 2026\n\t\t\t\t\t\t\t\t\t\tpresentation features the theme\n\t\t\t\t\t\t\t\t\t\t<strong>'Jololipi' (জললিপি)</strong>. The concept evokes the\n\t\t\t\t\t\t\t\t\t\tidea of a script formed in water, creating a poetic\n\t\t\t\t\t\t\t\t\t\tconnection between water, memory, and expression, brought to\n\t\t\t\t\t\t\t\t\t\tlife by <strong>Team Sanatan Dinda</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/NalinSarkarStreetSarbojoninDurgotsab" }, { type: LinkType.WEBSITE, value: "https://www.instagram.com/streetnalinsarkar" }, { type: LinkType.WEBSITE, value: "https://www.youtube.com/@nalinsarkarstreetsarbojani5976" }, { type: LinkType.PHONE, value: "9830241410" }, { type: LinkType.EMAIL, value: "n3sd17@gmail.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5944002,88.370625,17z?entry=ttu" },
		{ order: 16, type: ItemType.PANDAL, area: Area.HATIBAGAN, title: "North Tridhara", distance: 290, gmapsUrl: "https://maps.app.goo.gl/32YxHmYVZd8CQrhS6", htmlDesc: "A North Kolkata neighbourhood puja included in the Hatibagan\n\t\t\t\t\t\t\t\t\t\tcircuit. Reliable information confirming a specific\n\t\t\t\t\t\t\t\t\t\t<strong>2026 theme or artist</strong> is not currently\n\t\t\t\t\t\t\t\t\t\tavailable, so this stop is kept intentionally general rather\n\t\t\t\t\t\t\t\t\t\tthan attributing an unverified concept to the committee.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/NorthTridharaclub" }, { type: LinkType.PHONE, value: "9836637777" }, { type: LinkType.EMAIL, value: "tridhara.club1950@gmail.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5958155,88.3733659,17z?entry=ttu" },
		{ order: 17, type: ItemType.PANDAL, area: Area.HATIBAGAN, title: "Hatibagan Nabinpally", distance: 350, gmapsUrl: "https://maps.app.goo.gl/3wBxpxS8iivZirxC6", htmlDesc: "Celebrating its <strong>93rd year</strong>, this\n\t\t\t\t\t\t\t\t\t\tlong-running Hatibagan-area puja forms an integral part of\n\t\t\t\t\t\t\t\t\t\tthe traditional North Kolkata circuit. The 2026 presentation\n\t\t\t\t\t\t\t\t\t\tfeatures the theme\n\t\t\t\t\t\t\t\t\t\t<strong>'Hashi Khushi Pujo - Choto Thakar Boro Moja' (হাসি খুশি\n\t\t\t\t\t\t\t\t\t\t\tপুজো - ছোট থাকার বড় মজা)</strong>, conceptualised by <strong>Shankar Pal</strong>, with an\n\t\t\t\t\t\t\t\t\t\tidol crafted by <strong>Arighna Saha</strong>, lighting by\n\t\t\t\t\t\t\t\t\t\t<strong>Dipankar Dey</strong>, and music by\n\t\t\t\t\t\t\t\t\t\t<strong>Gautam Ghosh</strong>.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/nabinpally.hatibagan" }, { type: LinkType.WEBSITE, value: "https://www.youtube.com/@hatibagan-nabinpally" }, { type: LinkType.PHONE, value: "9831220088" }, { type: LinkType.EMAIL, value: "hatibagan.nabinpally@gmail.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5956128,88.3725817,17z?entry=ttu" },
		{ order: 18, type: ItemType.PANDAL, area: Area.SOVABAZAR, title: "Sovabazar Rajbari", distance: 850, gmapsUrl: "https://maps.app.goo.gl/hdLF2o85A5YrR7JE9", htmlDesc: "Celebrating its <strong>269th year</strong>, this iconic\n\t\t\t\t\t\t\t\t\t\tbonedi bari (household) puja was established in\n\t\t\t\t\t\t\t\t\t\t<strong>1757 by Raja Nabakrishna Deb</strong>. Held in the\n\t\t\t\t\t\t\t\t\t\tgrand Nat Mandap, it is renowned for its traditional\n\t\t\t\t\t\t\t\t\t\t<strong>Ek-chala sabeki idol</strong>, ancient family\n\t\t\t\t\t\t\t\t\t\trituals, and a rich heritage that has hosted historical\n\t\t\t\t\t\t\t\t\t\tfigures from Lord Clive to Rabindranath Tagore.", links: [{ type: LinkType.WEBSITE, value: "https://www.facebook.com/sovabazar.rajbari.official" }, { type: LinkType.PHONE, value: "7595985168" }, { type: LinkType.EMAIL, value: "sovabazarrajbari@yahoo.com" }], toiletsUrl: "https://www.google.com/maps/search/toilets/@22.5962643,88.362616,17z?entry=ttu", transit: 3 }
	],
	transits: [
		{ index: 0, steps: [{ order: 1, medium: TransitMedium.CAB, src: TransitPlaces.P_SONARPUR_JUNCTION, dest: TransitPlaces.P_BAGBAZAR_SARBOJANIN }] },
		{ index: 1, steps: [{ order: 1, medium: TransitMedium.BUS, src: TransitPlaces.P_SOVABAZAR_METRO_STATION, dest: TransitPlaces.P_JORASANKO_THAKUR_BARI }] },
		{ index: 2, steps: [{ order: 1, medium: TransitMedium.BUS, src: TransitPlaces.P_RAM_MANDIR, dest: TransitPlaces.P_CHALTA_BAGAN }] },
		{ index: 3, steps: [{ order: 1, medium: TransitMedium.CAB, src: TransitPlaces.P_SOVABAZAR_RAJBARI, dest: TransitPlaces.P_SONARPUR_JUNCTION }] }
	],
};
